services:
  mongo:
    image: mongo:6
    container_name: hedera-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: hedera

volumes:
  mongo-data:
